export const ROOT_PATH = '/'
export const COUNTER_PAGE_PATH = '/counter'
export const RESTAURANT_PAGE_PATH = '/restaurant'
export const CART_PAGE_PATH = '/cart'
export const ORDER_COMPLETE_PAGE_PATH = '/order/complete'
